apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-dba0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-dba0
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-dba0
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-dba0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-dba0
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-jvnj-tenant/appstudio/dc-metro-map-dba0@sha256:3f9fc091c7972b4c1ec1341e869e663e902e6daef9b7eb2e1f660a29a624bba7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
